### ISSUE TITLE
make robot go to correct position after detect custom sleeve

### ISSUE THREAD

**Issue by 12sliu** [Brighton-FTC/FTC-2023#46]
if we cannot get roadrunner working, we should be able to just manually make the motors turn for x amount of time right? It's messy but it'll get us 20 points. Probably treat as backup

note: go to tagDetection in CV at line 170 if you want to work on this

**Comment by WebCoder49** [comment]
@micnekr said:
**Please note that I made changes to both master and bclib, you would need to pull both. Roadrunner will probably not work because it has a very weird bug we haven't figured out, so forget about rr and use the HDriveWrapper (or some replacement for that, e.g. driving the motors directly) to drive to the desired positions using encoders or timing. I would suggest you avoid turning (but keep the HDriveWrapper PID + relative motion so that the robot doesn't go too off course when it turns when driving due to mechanics being wonky). In general, it's up to you to decide how to approach this, I just gave you most information I had to let you start off at almost full speed because we don't have much time until the doomsday.**

**Comment by 12sliu** [comment]
ok so I want to try and understand what we're doing, how do we determine the distance that the drivetrain can travel in a tick without knowing max velocity? We could just do lots of repetitive testing to get the distances just right, but that would take too much time wouldn't it? sorry for annoying you while you're busy

**Comment by WebCoder49** [comment]
Done
